name: Test Database Migrations

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - staging
      - development
  # for debugging purpose
  workflow_dispatch:

jobs:
  test-migrate:
    name: Test DB Migrations
    runs-on: ubuntu-latest

    container: golang:1.25.3-alpine

    services:
      postgres:
        image: postgres:17.4-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          MIGRATE_VERSION: v4.19.1
          MIGRATE_OS: linux
          MIGRATE_ARCH: amd64
        run: |
          apk add --no-cache make curl
          curl -L https://github.com/golang-migrate/migrate/releases/download/${{ env.MIGRATE_VERSION }}/migrate.${{ env.MIGRATE_OS }}-${{ env.MIGRATE_ARCH }}.tar.gz -o migrate.linux-amd64.tar.gz && \
            tar -xvzf migrate.linux-amd64.tar.gz && \
            mv migrate /usr/local/bin/migrate && \
            rm migrate.linux-amd64.tar.gz

      - name: Test migrations
        working-directory: ./database-migrations
        env:
            DB_DEMO_MASTER_USER: test_user
            DB_DEMO_MASTER_PASSWORD: test_password
            DB_DEMO_MASTER_HOST: postgres
            DB_DEMO_MASTER_NAME: test_db
            DB_DEMO_MASTER_SSLMODE: disable
        run: |
          make migrate-up
          make migrate-down ALL=true
        