name: Test Database Migrations

on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
    branches:
      - "master"
      - "staging"
      - "development"
  # for debugging purpose
  workflow_dispatch:

jobs:
  test-migrate:
    name: Run DB Migrations
    runs-on: ubuntu-latest

    container: golang:1.25.3-alpine

    services:
      postgres:
        image: postgres:17.4-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add --no-cache make
