name: Test Database Migrations

on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
    branches:
      - "master"
      - "staging"
      - "development"
  # for debugging purpose
  workflow_dispatch:

jobs:
  test-migrate:
    name: Run DB Migrations
    runs-on: ubuntu-latest

    container: golang:1.25.3-alpine

    services:
      postgres:
        image: postgres:17.4-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          MIGRATE_VERSION: v4.19.1
        run: |
          apk add --no-cache make
          curl -L https://github.com/golang-migrate/migrate/releases/download/${{ env.MIGRATE_VERSION }}/migrate.linux-amd64.tar.gz -o migrate.linux-amd64.tar.gz && \
            tar -xvzf migrate.linux-amd64.tar.gz && \
            mv migrate /usr/local/bin/migrate && \
            rm migrate.linux-amd64.tar.gz
    
      - name: Test migrations
        run: make migrate-up
        working-directory: ./database-migrations
        env:
            DATABASE_DSN: "postgres://user:password@postgres:5432/test_db?sslmode=disable"
